spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

# --- Eureka client defaults ---
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka/}

# --- Actuator (for config refresh) ---
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
