server:
  port: 8001
spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/user_database
    username: root
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:master}
  client-id: ${KEYCLOAK_CLIENT_ID:salon-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:Z3cH23EFz7SRx09D60YU6pEnWxKtbI9L}
  scope: ${KEYCLOAK_SCOPE:openid profile email}
  internal-client-id: ${KEYCLOAK_INTERNAL_CLIENT_ID:a7c65638-49c5-4e12-a98e-1ddc94b60188}
  admin:
    username: ${KEYCLOAK_ADMIN_USER:clowderline}
    password: ${KEYCLOAK_ADMIN_PASSWORD:123456}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
